from .ai_report import AIReport
from .ai_report_image import AIReportImage
from .appointment import Appointment
from .clinic import Clinic
from .doctor import Doctor
from .medical_history import MedicalHistory
from .medicine import Medicine
from .medicine_search_history import MedicineSearchHistory
from .message import Message
from .notification import Notification
from .package import Package
from .patient import Patient
from .payment import Payment
from .plan import Plan
from .prescription import Prescription
from .review import Review
from .role import Role
from .speciality import Speciality
from .subscription import Subscription
from .user import User
